### ISSUE TITLE
Deprecate split collectives in MPI I/O

### ISSUE THREAD

**Issue by tonyskjellum** [mpi-forum/mpi-issues#467]
# Problem

The 12 functions MPI_FILE_READ_AT_ALL_BEGIN, MPI_FILE_READ_AT_ALL_END, MPI_FILE_WRITE_AT_ALL_BEGIN, MPI_FILE_WRITE_AT_ALL_END, MPI_FILE_READ_ALL_BEGIN, MPI_FILE_READ_ALL_END, MPI_FILE_WRITE_ALL_BEGIN, MPI_FILE_WRITE_ALL_END, MPI_FILE_READ_ORDERED_BEGIN, MPI_FILE_WRITE_ORDERED_END,MPI_FILE_READ_ORDERED_BEGIN, MPI_FILE_WRITE_ORDERED_END are deprecated and will be removed in the next major release of the MPI standard.

# Proposal

These functions are inferior to using the fully nonblocking collective operations in MPI IO provided in MPI-3.0.  
They are leftovers from MPI-2 where we didn't implement nonblocking collectives as we eventually did in MPI-3.
No one should need to use these. It is not apparent that many codes do use these.

# Changes to the Text

Appropriate changes to mark these functions as deprecated in the I/O chapter and appendices will be added.
Explanation of how to change from using these functions to using truly nonblocking APIs in the standard already
will be given to smooth the transition, if any, for users.

# Impact on Implementations

Implementations will probably keep these functions for many years after removal.  So, no impact on implementations for the foreseeable future till they strictly build for MPI that comes after MPI-5.

# Impact on Users

Potentially, some users will have to switch to using the nonblocking operations in existing codes over a period of many years.  New codes will be written using the truly nonblocking APIs.

# References and Pull Requests

TBD

**Comment by wgropp** [comment]
I support this - I pushed for the split collectives in MPI-2 when it was clear that nonblocking collectives would not be included in MPI 2. Its time to remove these (and make MPI slightly smaller!)

**Comment by rsth** [comment]
I agree.

**Comment by roblatham00** [comment]
No argument from me. The next time I see a code that uses the split collectives it will be the first time.

**Comment by qkoziol** [comment]
Agree - definitely not needed now.

**Comment by RolfRabenseifner** [comment]
I also fully agree that the split collectives should be deprecated,
but I do not understand, why the two nonblocking routines 
- MPI_FILE_IREAD_ORDERED
- MPI_FILE_IWRITE_ORDERED

are still missing in MPI-5.0.
See MPI-5.0 Table 14.1 page 650.
They would be needed if MPI_FILE_READ_ORDERED_BEGIN, MPI_FILE_READ_ORDERED_END, MPI_FILE_WRITE_ORDERED_BEGIN, and MPI_FILE_WRITE_ORDERED_END should be deprecated.
I thought that there is already an issue (and perhaps PR) for MPI_FILE_IREAD_ORDERED and MPI_FILE_IWRITE_ORDERED, but could not find it.
